export { default as Home } from "./Home"
export { default as Clothes } from "./Clothes"
export { default as Categories } from "./Categories"
export { default as Detail } from "./Detail"
export { default as About } from "./About"
export { default as Login } from "./Login"